# Generated by Django 4.2 on 2023-04-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='present',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time_in',
            new_name='shift_end',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time_out',
            new_name='shift_start',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='hours_worked',
        ),
    ]
